add install dir to env

diff --git a/.github/workflows/integration-check-install.yml b/.github/workflows/integration-check-install.yml
--- a/.github/workflows/integration-check-install.yml
+++ b/.github/workflows/integration-check-install.yml
@@ -15,11 +15,16 @@ jobs:
         run: ./scripts/install.sh
       - name: Validate Command is Installed
         run: |
-          if ! command -v /home/runner/.local/bin/bridgetokubernetes/dsc &> /dev/null
+          if command -v /home/runner/.local/bin/bridgetokubernetes/dsc &> /dev/null
           then
-              echo "B2K could not be found"
-              exit 1
+              echo "install_dir=/home/runner/.local/bin/bridgetokubernetes/dsc" >> $GITHUB_ENV
+          elif command -v /usr/local/bin/bridgetokubernetes/dsc &> /dev/null 
+          then
+            echo "install_dir=/usr/local/bin/bridgetokubernetes/dsc" >> $GITHUB_ENV
+          else 
+            echo "B2k CLI is not found"
+            exit 1
           fi
       - name: Validate B2k Command Runs
-        run: /home/runner/.local/bin/bridgetokubernetes/dsc connect --help
+        run: ${{ env.install_dir }} connect --help
     
